In [20]:
import pandas as pd

In [21]:
!wget "https://drive.google.com/uc?export=download&id=1E3bwvYGf1iWc0IXPN-mD bI "  -O "mcknisey.csv"

'wget' is not recognized as an internal or external command,
operable program or batch file.

In [22]:
df=pd.read_csv("a.csv")
df.sort_values(by="Dept")

,ID,Name,Age,Gender,City,Salary,Dept,Experience,Rating,Projects,Hours,Bonus,Status,JoinYear,LastProm,Leaves,Score,Team,Manager,Country
13,14,Anita,32,F,Pune,55000,Finance,8,4.4,5,170,8000,Active,2018,2022,10,89,B,No,India
23,24,Divya,27,F,Chennai,45000,Finance,5,4.0,3,155,5800,Active,2021,2023,6,83,B,No,India
29,30,Alka,26,F,Chennai,44000,Finance,4,4.1,3,150,5000,Active,2021,2023,6,82,C,No,India
20,21,Rakesh,37,M,Delhi,72000,Finance,11,4.8,7,180,10500,Active,2016,2021,13,92,A,Yes,India
38,39,Vinay,38,M,Delhi,77000,Finance,13,4.9,8,185,11200,Active,2015,2021,13,94,A,Yes,India
17,18,Shreya,26,F,Chennai,43000,Finance,4,4.1,3,150,5000,Active,2021,2023,6,82,C,No,India
32,33,Ajay,36,M,Delhi,74000,Finance,12,4.8,7,182,10800,Active,2016,2021,12,92,A,Yes,India
10,11,Deepak,36,M,Bangalore,75000,Finance,12,4.9,7,185,11000,Active,2017,2022,12,93,A,Yes,India
26,27,Raj,39,M,Delhi,78000,Finance,14,4.9,8,188,11500,Active,2015,2021,14,94,A,Yes,India
35,36,Pallavi,29,F,Chennai,48000,Finance,6,4.3,4,165,6500,Active,2019,2023,7,87,B,No,India
6,7,Anil,31,M,Chennai,52000,Finance,7,4.3,5,160,7200,Active,2019,2022,9,88,A,Yes,India
2,3,Sita,28,F,Pune,45000,Finance,4,4.5,4,165,6000,Active,2021,2023,6,85,A,Yes,India
9,10,Riya,24,F,Delhi,39000,HR,2,3.7,2,145,3500,Active,2023,2023,3,72,C,No,India
28,29,Kunal,35,M,Bangalore,69000,HR,10,4.5,6,175,9200,Active,2017,2022,11,90,A,Yes,India
1,2,Ravi,30,M,Mumbai,50000,HR,5,3.8,5,170,7000,Active,2020,2022,8,82,B,No,India
22,23,Varun,30,M,Bangalore,56000,HR,7,4.1,5,168,7200,Active,2019,2022,8,86,A,Yes,India
37,38,Geeta,25,F,Pune,42000,HR,3,3.9,2,150,4800,Active,2022,2023,4,78,C,No,India
5,6,Kiran,29,F,Hyderabad,48000,HR,6,3.9,4,175,6500,Active,2019,2021,7,80,B,No,India
31,32,Sneha,28,F,Pune,46000,HR,5,4.0,3,155,6000,Active,2020,2023,6,84,C,No,India
15,16,Kavita,27,F,Mumbai,46000,HR,5,3.9,3,155,6000,Active,2020,2023,5,81,B,No,India
25,26,Nisha,24,F,Pune,40000,HR,2,3.7,2,145,3500,Active,2023,2023,3,73,C,No,India
12,13,Suresh,40,M,Hyderabad,80000,HR,15,4.7,8,190,12000,Active,2015,2021,15,95,A,Yes,India
34,35,Sameer,31,M,Bangalore,56000,HR,7,4.1,5,170,7200,Active,2019,2022,8,86,A,Yes,India
19,20,Tina,25,F,Pune,41000,HR,3,3.8,2,148,4500,Active,2022,2023,4,76,C,No,India
30,31,Rohit,32,M,Hyderabad,58000,IT,7,4.4,5,168,7800,Active,2018,2022,9,88,B,Yes,India
36,37,Sunil,34,M,Hyderabad,61000,IT,8,4.6,6,175,8500,Active,2018,2022,10,90,A,Yes,India
33,34,Reena,27,F,Mumbai,47000,IT,5,4.2,4,160,6200,Active,2020,2023,6,85,B,No,India
0,1,Amit,25,M,Delhi,40000,IT,2,4.2,3,160,5000,Active,2022,2023,5,78,A,Yes,India
24,25,Akash,33,M,Hyderabad,62000,IT,8,4.6,6,172,8800,Active,2018,2022,10,91,A,Yes,India
21,22,Sonal,28,F,Mumbai,47000,IT,5,4.2,4,162,6000,Active,2020,2023,6,85,B,No,India
18,19,Arjun,31,M,Hyderabad,54000,IT,7,4.3,5,165,7500,Active,2019,2022,8,87,B,Yes,India
16,17,Nikhil,34,M,Bangalore,68000,IT,9,4.5,6,175,9000,Active,2017,2022,11,90,A,Yes,India
14,15,Manoj,29,M,Delhi,48000,IT,6,4.0,4,160,6500,Active,2019,2023,7,84,A,Yes,India
11,12,Meena,28,F,Chennai,47000,IT,5,4.2,4,165,6000,Active,2020,2023,6,86,B,No,India
8,9,Vikas,33,M,Mumbai,60000,IT,8,4.6,6,170,8500,Active,2018,2022,11,91,A,Yes,India
7,8,Pooja,27,F,Pune,46000,IT,4,4.1,3,155,5500,Active,2021,2023,6,83,B,No,India
4,5,Rohan,35,M,Bangalore,70000,IT,10,4.8,6,180,10000,Active,2018,2022,10,90,A,Yes,India
3,4,Neha,26,F,Delhi,42000,IT,3,4.0,2,150,4000,Active,2022,2023,4,75,C,No,India
27,28,Priya,29,F,Mumbai,50000,IT,6,4.3,4,165,6500,Active,2019,2023,7,87,B,No,India
39,40,Komal,26,F,Mumbai,45000,IT,4,4.1,3,155,5800,Active,2021,2023,6,83,B,No,India

In [23]:
df.head()

,ID,Name,Age,Gender,City,Salary,Dept,Experience,Rating,Projects,Hours,Bonus,Status,JoinYear,LastProm,Leaves,Score,Team,Manager,Country
0,1,Amit,25,M,Delhi,40000,IT,2,4.2,3,160,5000,Active,2022,2023,5,78,A,Yes,India
1,2,Ravi,30,M,Mumbai,50000,HR,5,3.8,5,170,7000,Active,2020,2022,8,82,B,No,India
2,3,Sita,28,F,Pune,45000,Finance,4,4.5,4,165,6000,Active,2021,2023,6,85,A,Yes,India
3,4,Neha,26,F,Delhi,42000,IT,3,4.0,2,150,4000,Active,2022,2023,4,75,C,No,India
4,5,Rohan,35,M,Bangalore,70000,IT,10,4.8,6,180,10000,Active,2018,2022,10,90,A,Yes,India

In [24]:
import numpy as np

In [25]:
df["Age"].value_counts()

Age
28    4
27    4
26    4
29    4
25    3
31    3
30    2
35    2
33    2
24    2
36    2
32    2
34    2
40    1
37    1
39    1
38    1
Name: count, dtype: int64

In [26]:
df.drop("Age",axis=1)

,ID,Name,Gender,City,Salary,Dept,Experience,Rating,Projects,Hours,Bonus,Status,JoinYear,LastProm,Leaves,Score,Team,Manager,Country
0,1,Amit,M,Delhi,40000,IT,2,4.2,3,160,5000,Active,2022,2023,5,78,A,Yes,India
1,2,Ravi,M,Mumbai,50000,HR,5,3.8,5,170,7000,Active,2020,2022,8,82,B,No,India
2,3,Sita,F,Pune,45000,Finance,4,4.5,4,165,6000,Active,2021,2023,6,85,A,Yes,India
3,4,Neha,F,Delhi,42000,IT,3,4.0,2,150,4000,Active,2022,2023,4,75,C,No,India
4,5,Rohan,M,Bangalore,70000,IT,10,4.8,6,180,10000,Active,2018,2022,10,90,A,Yes,India
5,6,Kiran,F,Hyderabad,48000,HR,6,3.9,4,175,6500,Active,2019,2021,7,80,B,No,India
6,7,Anil,M,Chennai,52000,Finance,7,4.3,5,160,7200,Active,2019,2022,9,88,A,Yes,India
7,8,Pooja,F,Pune,46000,IT,4,4.1,3,155,5500,Active,2021,2023,6,83,B,No,India
8,9,Vikas,M,Mumbai,60000,IT,8,4.6,6,170,8500,Active,2018,2022,11,91,A,Yes,India
9,10,Riya,F,Delhi,39000,HR,2,3.7,2,145,3500,Active,2023,2023,3,72,C,No,India
10,11,Deepak,M,Bangalore,75000,Finance,12,4.9,7,185,11000,Active,2017,2022,12,93,A,Yes,India
11,12,Meena,F,Chennai,47000,IT,5,4.2,4,165,6000,Active,2020,2023,6,86,B,No,India
12,13,Suresh,M,Hyderabad,80000,HR,15,4.7,8,190,12000,Active,2015,2021,15,95,A,Yes,India
13,14,Anita,F,Pune,55000,Finance,8,4.4,5,170,8000,Active,2018,2022,10,89,B,No,India
14,15,Manoj,M,Delhi,48000,IT,6,4.0,4,160,6500,Active,2019,2023,7,84,A,Yes,India
15,16,Kavita,F,Mumbai,46000,HR,5,3.9,3,155,6000,Active,2020,2023,5,81,B,No,India
16,17,Nikhil,M,Bangalore,68000,IT,9,4.5,6,175,9000,Active,2017,2022,11,90,A,Yes,India
17,18,Shreya,F,Chennai,43000,Finance,4,4.1,3,150,5000,Active,2021,2023,6,82,C,No,India
18,19,Arjun,M,Hyderabad,54000,IT,7,4.3,5,165,7500,Active,2019,2022,8,87,B,Yes,India
19,20,Tina,F,Pune,41000,HR,3,3.8,2,148,4500,Active,2022,2023,4,76,C,No,India
20,21,Rakesh,M,Delhi,72000,Finance,11,4.8,7,180,10500,Active,2016,2021,13,92,A,Yes,India
21,22,Sonal,F,Mumbai,47000,IT,5,4.2,4,162,6000,Active,2020,2023,6,85,B,No,India
22,23,Varun,M,Bangalore,56000,HR,7,4.1,5,168,7200,Active,2019,2022,8,86,A,Yes,India
23,24,Divya,F,Chennai,45000,Finance,5,4.0,3,155,5800,Active,2021,2023,6,83,B,No,India
24,25,Akash,M,Hyderabad,62000,IT,8,4.6,6,172,8800,Active,2018,2022,10,91,A,Yes,India
25,26,Nisha,F,Pune,40000,HR,2,3.7,2,145,3500,Active,2023,2023,3,73,C,No,India
26,27,Raj,M,Delhi,78000,Finance,14,4.9,8,188,11500,Active,2015,2021,14,94,A,Yes,India
27,28,Priya,F,Mumbai,50000,IT,6,4.3,4,165,6500,Active,2019,2023,7,87,B,No,India
28,29,Kunal,M,Bangalore,69000,HR,10,4.5,6,175,9200,Active,2017,2022,11,90,A,Yes,India
29,30,Alka,F,Chennai,44000,Finance,4,4.1,3,150,5000,Active,2021,2023,6,82,C,No,India
30,31,Rohit,M,Hyderabad,58000,IT,7,4.4,5,168,7800,Active,2018,2022,9,88,B,Yes,India
31,32,Sneha,F,Pune,46000,HR,5,4.0,3,155,6000,Active,2020,2023,6,84,C,No,India
32,33,Ajay,M,Delhi,74000,Finance,12,4.8,7,182,10800,Active,2016,2021,12,92,A,Yes,India
33,34,Reena,F,Mumbai,47000,IT,5,4.2,4,160,6200,Active,2020,2023,6,85,B,No,India
34,35,Sameer,M,Bangalore,56000,HR,7,4.1,5,170,7200,Active,2019,2022,8,86,A,Yes,India
35,36,Pallavi,F,Chennai,48000,Finance,6,4.3,4,165,6500,Active,2019,2023,7,87,B,No,India
36,37,Sunil,M,Hyderabad,61000,IT,8,4.6,6,175,8500,Active,2018,2022,10,90,A,Yes,India
37,38,Geeta,F,Pune,42000,HR,3,3.9,2,150,4800,Active,2022,2023,4,78,C,No,India
38,39,Vinay,M,Delhi,77000,Finance,13,4.9,8,185,11200,Active,2015,2021,13,94,A,Yes,India
39,40,Komal,F,Mumbai,45000,IT,4,4.1,3,155,5800,Active,2021,2023,6,83,B,No,India